spring:
  mail:
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    debug: true
    default-encoding: UTF-8

    host: smtp.mail.ru
    password: 5qLimVtwQ6XRen5habnS
    port: 465
    protocol: smtps
    smtp:
      auth: true
      starttls:
        enable: true
    username: innlab@gmail.com
  profiles: development
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: 1


server:
  servlet:
    context-path: /mail
  port: 9999

security:
  oauth2:
    client:
      client-id: mail-service
      client-secret: ${MAIL_SERVICE_PASSWORD}
      access-token-uri: http://localhost:5001/uaa/oauth/token
      grant-type: client_credentials
      scope: server
